package org.safehaus.chop.plugin;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Date;
import java.util.Properties;

import org.codehaus.plexus.util.FileUtils;
import org.safehaus.chop.api.Project;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;

import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.Bucket;
import com.fasterxml.jackson.databind.JsonMappingException;


/** Deploys the perftest.war created by war goal to S3 bucket using supplied configuration parameters */
@Mojo(name = "deploy" )
public class DeployMojo extends MainMojo {


    protected DeployMojo( MainMojo mojo ) {
        this.failIfCommitNecessary = mojo.failIfCommitNecessary;
        this.localRepository = mojo.localRepository;
        this.accessKey = mojo.accessKey;
        this.secretKey = mojo.secretKey;
        this.bucketName = mojo.bucketName;
        this.destinationParentDir = mojo.destinationParentDir;
        this.managerAppUsername = mojo.managerAppUsername;
        this.managerAppPassword = mojo.managerAppPassword;
        this.testPackageBase = mojo.testPackageBase;
        this.runnerSSHKeyFile = mojo.runnerSSHKeyFile;
        this.amiID = mojo.amiID;
        this.awsSecurityGroup = mojo.awsSecurityGroup;
        this.runnerKeyPairName = mojo.runnerKeyPairName;
        this.runnerName = mojo.runnerName;
        this.instanceType = mojo.instanceType;
        this.setupTimeout = mojo.setupTimeout;
        this.minimumRunners = mojo.minimumRunners;
        this.maximumRunners = mojo.maximumRunners;
        this.securityGroupExceptions = mojo.securityGroupExceptions;
        this.availabilityZone = mojo.availabilityZone;
        this.resetIfStopped = mojo.resetIfStopped;
        this.coldRestartTomcat = mojo.coldRestartTomcat;
        this.plugin = mojo.plugin;
        this.project = mojo.project;
    }


    @SuppressWarnings( "UnusedDeclaration" )
    protected DeployMojo() {
    }


    @Override
    public void execute() throws MojoExecutionException {
        String sourceFile = getWarToUploadPath();
        String destinationFile = getWarOnS3Path();
        String projectFileKey = getProjectFilePath();
        File source = new File( sourceFile );

        if ( ! isReadyToDeploy() ) {
            getLog().info( "War is not ready to upload to store, calling chop:war goal now..." );
            WarMojo warMojo = new WarMojo( this );
            warMojo.execute();
        }

        if ( ! isReadyToDeploy() ) {
            throw new MojoExecutionException( "Files to be deployed are not ready and chop:war failed" );
        }

        String configPropertiesFilePath = getExtractedWarRootPath() + "WEB-INF/classes/" + PROJECT_FILE;
        FileUtils.mkdir( configPropertiesFilePath.substring( 0, configPropertiesFilePath.lastIndexOf( '/' ) ) );

        try {
            // Write deploy time to loadTime property in project.properties
            Properties props = new Properties();
            props.load( new FileInputStream( configPropertiesFilePath ) );
            props.setProperty( Project.LOAD_TIME_KEY, Utils.getTimestamp( new Date() ) );

            OutputStream out = new FileOutputStream( configPropertiesFilePath );
            props.store( out, "Generated by chop:deploy" );
        }
        catch ( JsonMappingException e ) {
            throw new MojoExecutionException( "Project.json file format is faulty", e );
        }
        catch ( IOException e ) {
            throw new MojoExecutionException( "Error while modifying " + PROJECT_FILE + " file", e );
        }


        AmazonS3 s3 = Utils.getS3Client( accessKey, secretKey );

        if ( !s3.doesBucketExist( bucketName ) ) {
            Bucket bucket = s3.createBucket( bucketName );
            if( bucket == null ) {
                throw new MojoExecutionException( "Bucket " + bucketName + " doesn't exist and could not create one" );
            }
            else {
                getLog().info( "Bucket " + bucketName + " didn't exist, created a new one" );
            }
        }

        getLog().info( "Uploading file to: " + destinationFile );

        boolean success = Utils.uploadToS3( s3, bucketName, destinationFile, source );
        if ( !success ) {
            throw new MojoExecutionException( "Unable to upload war file to S3." );
        }

        success = Utils.uploadToS3( s3, bucketName, projectFileKey, new File( configPropertiesFilePath ) );
        if ( !success ) {
            throw new MojoExecutionException( "Unable to upload $PROJECT_FILE file to S3." );
        }

        getLog().info( "File " + source + " uploaded to s3://" + bucketName + "/" + destinationFile );
    }


    private boolean isReadyToDeploy() {
        File source = new File( getWarToUploadPath() );
        try {
            if ( ! source.exists() ) {
                return false;
            }

            File extractedConfigPropFile = new File( getExtractedWarRootPath() + "WEB-INF/classes/project.properties" );
            if ( extractedConfigPropFile.exists() ) {
                Properties props = new Properties();
                FileInputStream inputStream = new FileInputStream( extractedConfigPropFile );
                props.load( inputStream );
                inputStream.close();

                String commitId = Utils.getLastCommitUuid( Utils.getGitConfigFolder( getProjectBaseDirectory() ) );
                return commitId.equals( props.getProperty( Project.GIT_UUID_KEY ) );
            }
        } catch ( Exception e ) {
            getLog().warn( e );
        }
        return false;
    }
}
